### ISSUE TITLE
How to transition circuit from open to halfOpen state without waiters.

### ISSUE THREAD

**Issue by waruwaruwaru** [nodeshift/opossum#580] opened 2021-06-16 21:29 UTC
## Steps to Produce Error:

````
const Breaker = require("opossum");

function failFunction() {
    return new Promise((resolve, reject) => {
        setTimeout(() => { reject("rejected") }, 1000);
    })
}

const cb = new Breaker(failFunction, {
    resetTimeout: 10000
})

function wait() {
    return new Promise((resolve, reject) => {
        setTimeout(() => { resolve() }, 1000);
    })
}

(async () => {
    while (true) {
        try {
            let res = await cb.fire();
            console.log("result: ", res);
            // await wait();
        } catch (e) {
            console.log("error: ", e);
            // await wait();
        }
    }
})();
````
Hi NodeShift team, I have a case where the circuit breaker state does not transition from open -> halfOpen if I do not provide a timer. Here in this code, I have a function called failFunction that will reject a promise to force the circuit to be in an open state. By default, the circuit will wait 30 seconds before transitioning to a halfOpen state but if I never add a waiter then the code will keep running and the opossum's library setTimeout callback function (https://github.com/nodeshift/opossum/blob/main/lib/circuit.js#L217-L227) would never get called. I was wondering if there is a good way to get the circuit transition from an open state to a halfOpen state without using a waiter?

**Comment by lance** [comment] 2021-06-18 15:50
Hi @waruwaruwaru looking at the code here, you never give the circuit breaker enough time to enter the `halfOpen` state. That only happens if there have been no failures for 10 seconds (the `resetTimeout` option), but your code is calling `cb.fire()` every second if you remove `wait()` and every two seconds if you keep it in. I made some changes to this example code that might help clarify how the state transition works.

```js
const Breaker = require("opossum");

let count = 0
function failFunction() {
    console.log("invocation ", ++count);
    return new Promise((resolve, reject) => {
        setTimeout(() => { 
            if (count%3 === 0) {
                resolve("resolved")
            } else {
                reject("rejected") 
            }
        }, 1000)
    })
}

const cb = new Breaker(failFunction, {
    resetTimeout: 5000
})

for (const event of 
    [ 'open', 'close', 'halfOpen', 'success', 'failure', 'reject' ]) {
    cb.on(event, d => console.log(event));
}

function wait(l=1000) {
    return new Promise((resolve, reject) => {
        setTimeout(() => { resolve() }, l);
    })
}

(async () => {
    while (true) {
        try {
            let res = await cb.fire();
        } catch (e) {
            console.log("waiting 5 seconds")
            await wait(5000);
        }
    }
})();
```

**Comment by waruwaruwaru** [comment] 2021-06-18 17:23
@lance thank you for getting back to me. When I set the circuit breaker's resetTimeout to 10 second but set the waiter to timeout for 2 second, it still help me transition to the halfOpen state after calling the waiter 5 times. As long as I've waited 10 seconds total whether its in one call or multiple calls it will help the state transition to a halfOpen state.

But I was wondering if there is any way to transition to a halfOpen state without using any waiters?

**Comment by lance** [comment] 2021-06-18 21:11
> But I was wondering if there is any way to transition to a halfOpen state without using any waiters?

The timeout just has to occur - after 10 seconds, it transitions to halfOpen no matter what. I'm not sure I'm following what you are after.

**Comment by waruwaruwaru** [comment] 2021-06-18 21:30
If I run the code without any waiters, even after 10 seconds, I do not see the halfOpen state gets emitted. Is this because the code ran many executions in the while loop that it never got a chance to emit the "halfOpen" event?

**Comment by lance** [comment] 2021-06-23 22:58
> If I run the code without any waiters, even after 10 seconds, I do not see the halfOpen state gets emitted. Is this because the code ran many executions in the while loop that it never got a chance to emit the "halfOpen" event?

The short answer is "yes". But the long answer is that this behavior _is_ a little confusing and I am not sure that I can explain exactly what is going on here in the event loop. For example, the output from `console.log()` in the `catch` block comes at a rate much faster than once per second. This is because `console.log()` is also async (not exactly, but it writes to standard out asynchronously). You can try modifying your example to use `fs.writeSync(1, err)` but I doubt that will change anything. I'm going to spend some time playing around with this example to better understand what's going on and whether or not there are implications for opossum. Thanks for bringing it up.

**Comment by mhdawson** [comment] 2021-06-24 19:29
So I think this comes down to "don't block the event loop". Node.js never preempts running JavaScript code to do something else. The code is calling await cb.fire() as fast as it can.  

We can start by looking at this picture of the event loop: 

![image](https://user-images.githubusercontent.com/9373002/123316144-86002100-d4fa-11eb-834b-89f3fc958d18.png)

However, that does not really shed any light as I think the problem is related to the fact that with promises (which are what underlies await) there is also a microtask queue. As the event loop tries to exit one of those yellow JS boxes, it first works to empy the microtask queue before it does so. This article talks about the issue at a high level: https://medium.com/dkatalis/eventloop-in-nodejs-macrotasks-and-microtasks-164417e619b9

The net is that the loop constantly generates more microtasks (I think the opposum doc says that one a certain number of calls to fire are received they reject immediately which might be contributing) preventing the application from exiting the first yellow JS box in the event loop and we never get to the yellow JS box were we will run the JavaScript for Timers. This is an article that talks about the specific issue: https://snyk.io/blog/nodejs-how-even-quick-async-functions-can-block-the-event-loop-starve-io/.  

I'd have to do more investigation to be sure that we never exit the yellow JS box or simply overload by generating so many cf.fire() calls, but either way it effectively blocks the event loop.  If you run the existing code and use `top` or something similar you'll see that Node.js is consuming a lot of cpu in that tight loop.

This is a re-written version that performs as expected:

```JavaScript
async () => {
  setInterval(async () => {
    try {
      let res = await cb.fire();
      console.log("result: ", res);
     } catch (e) {
       console.log("error: ", e);
     }
  }, 1000);
  */
})();

```

and if you look at the output from `top` the cpu usage is negligible.

**Comment by lance** [comment] 2021-06-24 19:40
Thanks for chiming in @mhdawson - your insight is really helpful.

**Comment by lance** [comment] 2021-06-30 17:17
Closing this as there does not seem to be anything required of the library

**Closed by lance** 2021-06-30 17:17 UTC
Labels: question
